paths:
  static: ''
  uploads: uploads
timezone: America/Chicago
markdown:
  engine: commonmark
  options:
    html: true
collections_config:
  pages:
    path: ''
    icon: wysiwyg
  admin:
    path: admin
    icon: ad
  data:
    path: _data
    icon: data_usage
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
